# The URL the site will be built for
base_url = "https://example.com"

# The site title and description; used in feeds by default.
title = "archie-zola"
description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags"}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# control dark mode: auto | dark | toggle
mode = "toggle"
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

# interal CDN resource
useCDN = false

favicon = "/icon/favicon.png"

copyright = "keith"

[[extra.menu]]
name = "Home"
url = "/"
weight = 1

[[extra.menu]]
name = "All posts"
url = "/posts"
weight = 2

[[extra.menu]]
name = "About"
url = "/about"
weight = 3

[[extra.menu]]
name = "Tags"
url = "/tags"
weight = 4

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/athul/archie"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://github.com/athulcajay/"

[[extra.social]]
icon = "gitlab"
name = "GitLab"
url = "https://gitlab.com/athul/"

